#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ASPNETDB")]
public partial class FeladatokDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertFeladatok(Feladatok instance);
  partial void UpdateFeladatok(Feladatok instance);
  partial void DeleteFeladatok(Feladatok instance);
  #endregion
	
	public FeladatokDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ASPNETDBConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public FeladatokDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public FeladatokDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public FeladatokDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public FeladatokDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Feladatok> Feladatoks
	{
		get
		{
			return this.GetTable<Feladatok>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Feladatok")]
public partial class Feladatok : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _Nev;
	
	private string _Leiras_Rovid;
	
	private string _Leiras_Hosszu;
	
	private string _Felev;
	
	private string _Tulajdonos;
	
	private string _Statusz;
	
	private int _Jegy;
	
	private string _Jelentkezett;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNevChanging(string value);
    partial void OnNevChanged();
    partial void OnLeiras_RovidChanging(string value);
    partial void OnLeiras_RovidChanged();
    partial void OnLeiras_HosszuChanging(string value);
    partial void OnLeiras_HosszuChanged();
    partial void OnFelevChanging(string value);
    partial void OnFelevChanged();
    partial void OnTulajdonosChanging(string value);
    partial void OnTulajdonosChanged();
    partial void OnStatuszChanging(string value);
    partial void OnStatuszChanged();
    partial void OnJegyChanging(int value);
    partial void OnJegyChanged();
    partial void OnJelentkezettChanging(string value);
    partial void OnJelentkezettChanged();
    #endregion
	
	public Feladatok()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nev", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
	public string Nev
	{
		get
		{
			return this._Nev;
		}
		set
		{
			if ((this._Nev != value))
			{
				this.OnNevChanging(value);
				this.SendPropertyChanging();
				this._Nev = value;
				this.SendPropertyChanged("Nev");
				this.OnNevChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Leiras_Rovid", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
	public string Leiras_Rovid
	{
		get
		{
			return this._Leiras_Rovid;
		}
		set
		{
			if ((this._Leiras_Rovid != value))
			{
				this.OnLeiras_RovidChanging(value);
				this.SendPropertyChanging();
				this._Leiras_Rovid = value;
				this.SendPropertyChanged("Leiras_Rovid");
				this.OnLeiras_RovidChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Leiras_Hosszu", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
	public string Leiras_Hosszu
	{
		get
		{
			return this._Leiras_Hosszu;
		}
		set
		{
			if ((this._Leiras_Hosszu != value))
			{
				this.OnLeiras_HosszuChanging(value);
				this.SendPropertyChanging();
				this._Leiras_Hosszu = value;
				this.SendPropertyChanged("Leiras_Hosszu");
				this.OnLeiras_HosszuChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Felev", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
	public string Felev
	{
		get
		{
			return this._Felev;
		}
		set
		{
			if ((this._Felev != value))
			{
				this.OnFelevChanging(value);
				this.SendPropertyChanging();
				this._Felev = value;
				this.SendPropertyChanged("Felev");
				this.OnFelevChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tulajdonos", DbType="NVarChar(256) NOT NULL", CanBeNull=false)]
	public string Tulajdonos
	{
		get
		{
			return this._Tulajdonos;
		}
		set
		{
			if ((this._Tulajdonos != value))
			{
				this.OnTulajdonosChanging(value);
				this.SendPropertyChanging();
				this._Tulajdonos = value;
				this.SendPropertyChanged("Tulajdonos");
				this.OnTulajdonosChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Statusz", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
	public string Statusz
	{
		get
		{
			return this._Statusz;
		}
		set
		{
			if ((this._Statusz != value))
			{
				this.OnStatuszChanging(value);
				this.SendPropertyChanging();
				this._Statusz = value;
				this.SendPropertyChanged("Statusz");
				this.OnStatuszChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jegy", DbType="Int NOT NULL")]
	public int Jegy
	{
		get
		{
			return this._Jegy;
		}
		set
		{
			if ((this._Jegy != value))
			{
				this.OnJegyChanging(value);
				this.SendPropertyChanging();
				this._Jegy = value;
				this.SendPropertyChanged("Jegy");
				this.OnJegyChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jelentkezett", DbType="NVarChar(256)")]
	public string Jelentkezett
	{
		get
		{
			return this._Jelentkezett;
		}
		set
		{
			if ((this._Jelentkezett != value))
			{
				this.OnJelentkezettChanging(value);
				this.SendPropertyChanging();
				this._Jelentkezett = value;
				this.SendPropertyChanged("Jelentkezett");
				this.OnJelentkezettChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
