#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ASPNETDB")]
public partial class TanarokDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertTanarok(Tanarok instance);
  partial void UpdateTanarok(Tanarok instance);
  partial void DeleteTanarok(Tanarok instance);
  #endregion
	
	public TanarokDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["ASPNETDBConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public TanarokDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public TanarokDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public TanarokDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public TanarokDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Tanarok> Tanaroks
	{
		get
		{
			return this.GetTable<Tanarok>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tanarok")]
public partial class Tanarok : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ID;
	
	private string _Nev;
	
	private string _Rovid_leiras;
	
	private string _Email;
	
	private string _Konzultacios_ido;
	
	private string _Telefon;
	
	private string _Szoba;
	
	private string _Informacios_oldal;
	
	private string _Ertesites;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNevChanging(string value);
    partial void OnNevChanged();
    partial void OnRovid_leirasChanging(string value);
    partial void OnRovid_leirasChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnKonzultacios_idoChanging(string value);
    partial void OnKonzultacios_idoChanged();
    partial void OnTelefonChanging(string value);
    partial void OnTelefonChanged();
    partial void OnSzobaChanging(string value);
    partial void OnSzobaChanged();
    partial void OnInformacios_oldalChanging(string value);
    partial void OnInformacios_oldalChanged();
    partial void OnErtesitesChanging(string value);
    partial void OnErtesitesChanged();
    #endregion
	
	public Tanarok()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ID
	{
		get
		{
			return this._ID;
		}
		set
		{
			if ((this._ID != value))
			{
				this.OnIDChanging(value);
				this.SendPropertyChanging();
				this._ID = value;
				this.SendPropertyChanged("ID");
				this.OnIDChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nev", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
	public string Nev
	{
		get
		{
			return this._Nev;
		}
		set
		{
			if ((this._Nev != value))
			{
				this.OnNevChanging(value);
				this.SendPropertyChanging();
				this._Nev = value;
				this.SendPropertyChanged("Nev");
				this.OnNevChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rovid_leiras", DbType="NVarChar(500)")]
	public string Rovid_leiras
	{
		get
		{
			return this._Rovid_leiras;
		}
		set
		{
			if ((this._Rovid_leiras != value))
			{
				this.OnRovid_leirasChanging(value);
				this.SendPropertyChanging();
				this._Rovid_leiras = value;
				this.SendPropertyChanged("Rovid_leiras");
				this.OnRovid_leirasChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(100)")]
	public string Email
	{
		get
		{
			return this._Email;
		}
		set
		{
			if ((this._Email != value))
			{
				this.OnEmailChanging(value);
				this.SendPropertyChanging();
				this._Email = value;
				this.SendPropertyChanged("Email");
				this.OnEmailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Konzultacios_ido", DbType="NVarChar(100)")]
	public string Konzultacios_ido
	{
		get
		{
			return this._Konzultacios_ido;
		}
		set
		{
			if ((this._Konzultacios_ido != value))
			{
				this.OnKonzultacios_idoChanging(value);
				this.SendPropertyChanging();
				this._Konzultacios_ido = value;
				this.SendPropertyChanged("Konzultacios_ido");
				this.OnKonzultacios_idoChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Telefon", DbType="NVarChar(100)")]
	public string Telefon
	{
		get
		{
			return this._Telefon;
		}
		set
		{
			if ((this._Telefon != value))
			{
				this.OnTelefonChanging(value);
				this.SendPropertyChanging();
				this._Telefon = value;
				this.SendPropertyChanged("Telefon");
				this.OnTelefonChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Szoba", DbType="NVarChar(100)")]
	public string Szoba
	{
		get
		{
			return this._Szoba;
		}
		set
		{
			if ((this._Szoba != value))
			{
				this.OnSzobaChanging(value);
				this.SendPropertyChanging();
				this._Szoba = value;
				this.SendPropertyChanged("Szoba");
				this.OnSzobaChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Informacios_oldal", DbType="NVarChar(100)")]
	public string Informacios_oldal
	{
		get
		{
			return this._Informacios_oldal;
		}
		set
		{
			if ((this._Informacios_oldal != value))
			{
				this.OnInformacios_oldalChanging(value);
				this.SendPropertyChanging();
				this._Informacios_oldal = value;
				this.SendPropertyChanged("Informacios_oldal");
				this.OnInformacios_oldalChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ertesites", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
	public string Ertesites
	{
		get
		{
			return this._Ertesites;
		}
		set
		{
			if ((this._Ertesites != value))
			{
				this.OnErtesitesChanging(value);
				this.SendPropertyChanging();
				this._Ertesites = value;
				this.SendPropertyChanged("Ertesites");
				this.OnErtesitesChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
